"""initial schema

Revision ID: 720addad51ae
Revises:
Create Date: 2026-10-03 02:10:03.151424
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '720addad51ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('daily_counters',
    sa.Column('counter_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('counter_date')
    )
    op.create_table('ranks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_number', sa.String(length=40), nullable=False),
    sa.Column('rank_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rank_code'], ['ranks.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_name'), 'patients', ['name'], unique=False)
    op.create_index(op.f('ix_patients_service_number'), 'patients', ['service_number'], unique=True)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('anesthesia_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('token_date', sa.Date(), nullable=False),
    sa.Column('token_sequence', sa.Integer(), nullable=False),
    sa.Column('token_number', sa.String(length=30), nullable=False),
    sa.Column('proposed_surgery', sa.String(length=240), nullable=False),
    sa.Column('proposed_anesthetic', sa.String(length=80), nullable=False),
    sa.Column('consultation_status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_ot_date', sa.Date(), nullable=True),
    sa.Column('ot_serial', sa.Integer(), nullable=True),
    sa.Column('ot_table', sa.String(length=30), nullable=True),
    sa.Column('ward', sa.String(length=80), nullable=True),
    sa.Column('disease', sa.Text(), nullable=True),
    sa.Column('operation', sa.String(length=240), nullable=True),
    sa.Column('surgeon', sa.String(length=160), nullable=True),
    sa.Column('anesthesiologist', sa.String(length=160), nullable=True),
    sa.Column('asa_class', sa.String(length=10), nullable=True),
    sa.Column('ot_status', sa.String(length=30), nullable=False),
    sa.Column('status_note', sa.String(length=240), nullable=True),
    sa.Column('token_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('form_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_date', 'token_sequence', name='uq_case_daily_token')
    )
    op.create_index(op.f('ix_anesthesia_cases_consultation_status'), 'anesthesia_cases', ['consultation_status'], unique=False)
    op.create_index(op.f('ix_anesthesia_cases_created_at'), 'anesthesia_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_anesthesia_cases_ot_status'), 'anesthesia_cases', ['ot_status'], unique=False)
    op.create_index(op.f('ix_anesthesia_cases_patient_id'), 'anesthesia_cases', ['patient_id'], unique=False)
    op.create_index(op.f('ix_anesthesia_cases_scheduled_ot_date'), 'anesthesia_cases', ['scheduled_ot_date'], unique=False)
    op.create_index(op.f('ix_anesthesia_cases_token_date'), 'anesthesia_cases', ['token_date'], unique=False)
    op.create_index(op.f('ix_anesthesia_cases_token_number'), 'anesthesia_cases', ['token_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anesthesia_cases_token_number'), table_name='anesthesia_cases')
    op.drop_index(op.f('ix_anesthesia_cases_token_date'), table_name='anesthesia_cases')
    op.drop_index(op.f('ix_anesthesia_cases_scheduled_ot_date'), table_name='anesthesia_cases')
    op.drop_index(op.f('ix_anesthesia_cases_patient_id'), table_name='anesthesia_cases')
    op.drop_index(op.f('ix_anesthesia_cases_ot_status'), table_name='anesthesia_cases')
    op.drop_index(op.f('ix_anesthesia_cases_created_at'), table_name='anesthesia_cases')
    op.drop_index(op.f('ix_anesthesia_cases_consultation_status'), table_name='anesthesia_cases')
    op.drop_table('anesthesia_cases')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_patients_service_number'), table_name='patients')
    op.drop_index(op.f('ix_patients_name'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('ranks')
    op.drop_table('daily_counters')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
